name: build android
on:
  push: {tags:  ['v*']} #  Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

env:
  BUILD_NAME: krk2yuri_android

jobs:
  fetch_thirdparty_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: check thirdparty build
      id: check_thirdparty_build
      uses: actions/cache@v3
      with: 
        path: ./thirdparty/build
        key: thirdparty_build
    
    - name: fetch thirdparty build
      if: steps.check_thirdparty_build.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/YuriSizuku/Kirikiroid2Yuri/releases/download/deps/thirdparty_build.tar.gz
        tar xvzf thirdparty_build.tar.gz

  fetch_thirdparty_port:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: check thirdparty port
      id: check_thirdparty_port
      uses: actions/cache@v3
      with: 
        path: ./thirdparty/port
        key: thirdparty_port
    
    - name: fetch thirdparty port
      if: steps.check_thirdparty_port.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/YuriSizuku/Kirikiroid2Yuri/releases/download/deps/thirdparty_port.tar.gz
        tar xvzf thirdparty_port.tar.gz

  build_android:
    runs-on: ubuntu-20.04
    needs: 
      - fetch_thirdparty_build
      - fetch_thirdparty_port

    steps:
    - uses: actions/checkout@v3

    - name: get thirdparty build cache
      uses: actions/cache@v3
      with: 
        key: thirdparty_build
        path: ./thirdparty/build

    - name: get thirdparty port cache
      uses: actions/cache@v3
      with: 
        key: thirdparty_port
        path: ./thirdparty/port
   
    - uses: actions/setup-java@v3
      with:
        java-version:  |
            8
            11
        distribution: 'temurin'
        cache: gradle

    - name: build krkr2yuri android
      env:
        SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
        SIGN_STORE_PASS: ${{ secrets.SIGN_STORE_PASS }}
      run: |
        wget https://github.com/YuriSizuku/Kirikiroid2Yuri/releases/download/1.3.9_yuri/Kirikiroid2_yuri_1.3.9.apk
        7z x Kirikiroid2_yuri_1.3.9.apk assets
        sudo mkdir /build_android && sudo chmod 777 /build_android 
        cd project/android
        chmod +x ./gradlew 
        ./gradlew assembleDebug --no-daemon
    
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./build_android/outputs/apk/debug/*.apk"
        allowUpdates: "true"
        prerelease: "true"
        token: ${{ secrets.GITHUB_TOKEN }}